version: '3.9'

services:
  app:
    build: .
    container_name: tinyurl_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tinyurl
      - REDIS_URL=redis://redis
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: tinyurl_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tinyurl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: tinyurl_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: